#项目名
spring.application.name: appUpdate

#服务器配置
server:
  port: 8080
  tomcat.uri-encoding: UTF-8
  session-timeout: 30

#配置属性
author:
  name: 夏亚运
  csdnUrl: https://blog.csdn.net/qq_40147863/article/details/841944931

#spring相关配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.114.188.231:3306/myapp
    username: root
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
  #编码格式
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

#swagger配置
swagger:
  enabled: true
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.4.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  contact.name: xyy
  contact.url: http://blog.didispace.com
  contact.email: dyc87112@qq.com
  base-path: /**
  exclude-path: /error, /ops/**

#静态资源对外暴露的访问路径
file:
  staticAccessPath: /upload/**
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  #uploadFolder: /home/upload/
  uploadFolder: d://java/upload/

